name: Verify Code
runs:
  using: composite
  steps:
    - run: |
        chmod +x scripts/*
        pnpm format:check
        pnpm lint:check
        pnpm compile
        ./scripts/build.sh
      shell: bash
