name: Verify Code
runs:
  using: composite
  steps:
    - run: |
        chmod +x scripts/*
        pnpm format:check
        pnpm lint:no-fix
        pnpm compile
        pnpm build
      shell: bash
