name: Publish
on:
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        name: Install PNPM
        with:
          version: 7.0.0

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'

      - name: Not Published
        if: ${{ steps.changelog.outputs.skipped == 'true' }}
        run: |
          echo "Changelog was empty, skipping publishing"
          exit 1

      - name: Rebuild with latest version
        run: pnpm build

      - uses: JS-DevTools/npm-publish@v1
        name: Publish to NPM
        with:
          package: lib/package.json
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
