name: Publish
on:
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/install
      - uses: ./.github/actions/verify
      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'
      - name: Publish to GitHub Packages
        uses: ./.github/actions/publish
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          npmAuthToken: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
